name: Prepare Release
on:
  push:
    branches:
      - master
      - develop

jobs:
  prepare_release:
    name: Prepare Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.X_GITHUB_TOKEN }}

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build for Release
        run: npm run release

      - name: Create Release
        run: npx semantic-release
