name: Linting and Testing
on:
  push

jobs:
  lint_and_test:
    name: 'Lint and Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm ci

      # - name: Lint
      #   run: npm run lint

      # - name: Test
      #   run: npm run test
