name: Update Web UI
on:
  push:
    tags:
      - v*

jobs:
  update_web_ui:
    name: Update Web UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Web UI
        uses: actions/checkout@v2
        with:
          repository: 'aesop/aesop-web-ui'
          fetch-depth: 1
          ref: 'develop'
          token: ${{ secrets.X_GITHUB_TOKEN }}

      - name: Create variables
        run: |
          echo "::set-env name=GEL_VERSION::${GITHUB_REF#refs/*/}"
          echo "::set-env name=BRANCH_NAME::update-Gel-to-${GITHUB_REF#refs/*/}"

      - name: npm install
        run: npm install --save github:aesop/aesop-gel#$GEL_VERSION

      - name: Commit and push update
        run: |
          git config user.name "Gel Updater"
          git config user.email ""
          git add ./package*
          git checkout -b $BRANCH_NAME
          git commit -m "chore(update-gel): update Aesop Gel to ${GEL_VERSION}"
          git push --set-upstream origin $BRANCH_NAME

      - name: Create PR
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/aesop/aesop-web-ui/pulls \
          -d '{"title":"Update Aesop Gel to ${GEL_VERSION}","head":"${BRANCH_NAME}","base":"develop"}'
