name: Update Web UI
on:
  push:
    tags:
      - v*

jobs:
  update_web_ui:
    name: Update Web UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Checkout Web UI
        uses: actions/checkout@v2
        with:
          repository: 'aesop/aesop-web-ui'
          fetch-depth: 1
          ref: 'develop'
          token: ${{ secrets.X_GITHUB_TOKEN }}

      - name: Create variables
        run: |
          echo "::set-env name=GEL_VERSION::${GITHUB_REF#refs/*/}"
          echo "::set-env name=BRANCH_NAME::update-Gel-to-${GITHUB_REF#refs/*/}"

      - name: Update Gel
        run: npm install --save github:aesop/aesop-gel#$GEL_VERSION

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.X_GITHUB_TOKEN }}
            commit-message: Update Gel to ${{ env.GEL_VERSION }}
            title: Update Gel to ${{ env.GEL_VERSION }}
            branch: update-gel-to-${{ env.GEL_VERSION }}
