name: Update Web UI
on:
  push:
    tags:
      - v*

jobs:
  update_web_ui:
    name: Update Web UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Web UI
        uses: actions/checkout@v2
        with:
          repository: 'aesop/aesop-web-ui'
          fetch-depth: 1
          ref: 'develop'
          token: ${{ secrets.X_GITHUB_TOKEN }}

      - name: npm install
        run: npm install --save github:aesop/aesop-gel#$GITHUB_REF

      - name: Commit and push update
        run: |
          git config user.name "Gel Updater"
          git config user.email ""
          git add ./package*
          git checkout -b update-Gel-to-$GITHUB_REF
          git commit -m "chore(update-gel): update Aesop Gel to ${GITHUB_REF}"
          git push

      - name: Create PR
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/aesop/aesop-web-ui/pulls \
          -d '{"title":"update Aesop Gel to ${GITHUB_REF}","head":"update-Gel-to-${GITHUB_REF}","base":"develop"}'
